version: '3.8'

services:
  backend:
    build: ./backend
    command: python run.py
    ports:
      - "5001:5001"
      - "5443:5443"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://bookadmin:qweasdzxc9@db:5432/bookingsystem
      JWT_SECRET_KEY: 87654321
    volumes:
      - ./backend/data:/app/data
      - ./backend/key:/app/key
      - /etc/localtime:/etc/localtime:ro


  db:
    image: postgres:13
    environment:
      POSTGRES_USER: bookadmin
      POSTGRES_PASSWORD: qweasdzxc9
      POSTGRES_DB: bookingsystem
      TZ: Australia/Sydney
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro


  frontend:
    build: ./frontend 

  nginx:
    build: ./nginx 

    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/www.huoyingzhe.com.crt:/etc/nginx/ssl/www.huoyingzhe.com.crt
      - ./nginx/www.huoyingzhe.com.key:/etc/nginx/ssl/www.huoyingzhe.com.key
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
