version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./key:/etc/nginx/ssl
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - web

  web:
    build: .
    command: python run.py
    environment:
      - DATABASE_URL=postgresql://bookadmin:qweasdzxc9@db:5432/bookingsystem
      - JWT_SECRET_KEY=87654321
    volumes:
      - ./data:/app/data
      - /etc/localtime:/etc/localtime:ro

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: bookadmin
      POSTGRES_PASSWORD: qweasdzxc9
      POSTGRES_DB: bookingsystem
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro

volumes:
  postgres_data:
