version: '3.8'

services:
  web:
    build: .
    command: python run.py
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://bookadmin:qweasdzxc9@db:5432/bookingsystem
      - JWT_SECRET_KEY=87654321
    volumes:
      - ./data:/app/data
      - /etc/localtime:/etc/localtime:ro

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: bookadmin
      POSTGRES_PASSWORD: qweasdzxc9
      POSTGRES_DB: bookingsystem
      TZ: Australia/Sydney
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro

volumes:
  postgres_data:
