"""Initial migration

Revision ID: 0067089ad88b
Revises: 
Create Date: 2024-06-28 14:38:12.965177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0067089ad88b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CSE_staff',
    sa.Column('zid', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('faculty_name', sa.String(length=256), nullable=False),
    sa.Column('school_name', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('zid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('HDR_students',
    sa.Column('zid', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('faculty_name', sa.String(length=256), nullable=False),
    sa.Column('school_name', sa.String(length=256), nullable=False),
    sa.Column('degree', sa.String(length=128), nullable=False),
    sa.Column('other_roles_within_cse', sa.String(length=256), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('zid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('space',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_type', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('zid', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('user_type', sa.String(length=128), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('zid'),
    sa.UniqueConstraint('zid')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('booking_status', sa.String(length=128), nullable=False),
    sa.Column('is_request', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['space.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.zid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hot_desk_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('level', sa.String(length=128), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('room', sa.String(length=128), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('HDR_student_permission', sa.Boolean(), nullable=False),
    sa.Column('CSE_staff_permission', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['space.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('room_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('level', sa.String(length=128), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('HDR_student_permission', sa.Boolean(), nullable=False),
    sa.Column('CSE_staff_permission', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['space.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_detail')
    op.drop_table('hot_desk_detail')
    op.drop_table('booking')
    op.drop_table('users')
    op.drop_table('space')
    op.drop_table('HDR_students')
    op.drop_table('CSE_staff')
    # ### end Alembic commands ###
