"""Add building column

Revision ID: 0d1f6d66e4ad
Revises: e0345852d4c7
Create Date: 2024-06-22 20:33:53.752740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d1f6d66e4ad'
down_revision = 'e0345852d4c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CSE_staff', schema=None) as batch_op:
        batch_op.drop_constraint('CSE_staff_zid_key', type_='unique')
        batch_op.create_foreign_key(None, 'users', ['zid'], ['zid'])

    with op.batch_alter_table('HDR_students', schema=None) as batch_op:
        batch_op.drop_constraint('HDR_students_zid_key', type_='unique')
        batch_op.create_foreign_key(None, 'users', ['zid'], ['zid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('HDR_students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('HDR_students_zid_key', ['zid'])

    with op.batch_alter_table('CSE_staff', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('CSE_staff_zid_key', ['zid'])

    # ### end Alembic commands ###
