"""Initial migration

Revision ID: 7ea8ccf40355
Revises: 
Create Date: 2024-06-22 18:20:17.541971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea8ccf40355'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CSE_staff', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['zid'])

    with op.batch_alter_table('HDR_students', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['zid'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['zid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('HDR_students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('CSE_staff', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
