"""

Revision ID: 89f2fac96a47
Revises: b6319fc7d952
Create Date: 2024-06-22 13:54:40.816125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f2fac96a47'
down_revision = 'b6319fc7d952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('RoomDetail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('building', sa.String(length=128), nullable=False))
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('RoomDetail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('building')

    # ### end Alembic commands ###
