"""Add building column

Revision ID: 9d102962f675
Revises: 0d1f6d66e4ad
Create Date: 2024-06-22 20:37:23.553967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d102962f675'
down_revision = '0d1f6d66e4ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_detail', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'space', ['id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_detail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
