"""Add user_type column

Revision ID: b6319fc7d952
Revises: 
Create Date: 2024-06-21 15:17:52.223205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6319fc7d952'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CSE_staff', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['zid'])

    with op.batch_alter_table('HDR_students', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['zid'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.String(length=128), nullable=False))
        batch_op.create_unique_constraint(None, ['zid'])
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_type')

    with op.batch_alter_table('HDR_students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('CSE_staff', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
