"""Add building column

Revision ID: e0345852d4c7
Revises: 7ea8ccf40355
Create Date: 2024-06-22 20:23:36.557189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0345852d4c7'
down_revision = '7ea8ccf40355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint('booking_room_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'space', ['room_id'], ['id'])

    with op.batch_alter_table('room_detail', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_detail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('booking_room_id_fkey', 'room_detail', ['room_id'], ['id'])

    # ### end Alembic commands ###
