"""Add building column

Revision ID: e5a6e5d6edcb
Revises: 9d102962f675
Create Date: 2024-06-24 18:20:08.058931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5a6e5d6edcb'
down_revision = '9d102962f675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CSE_staff', schema=None) as batch_op:
        batch_op.drop_constraint('CSE_staff_zid_fkey', type_='foreignkey')

    with op.batch_alter_table('HDR_students', schema=None) as batch_op:
        batch_op.drop_constraint('HDR_students_zid_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('HDR_students', schema=None) as batch_op:
        batch_op.create_foreign_key('HDR_students_zid_fkey', 'users', ['zid'], ['zid'])

    with op.batch_alter_table('CSE_staff', schema=None) as batch_op:
        batch_op.create_foreign_key('CSE_staff_zid_fkey', 'users', ['zid'], ['zid'])

    # ### end Alembic commands ###
